### ISSUE TITLE
Missing docs on cookie encryption/signing

### ISSUE THREAD

**Issue by notramo** [martenframework/website#4]
Please add to the documentation:
- What encryption and signature algorithm do the encrypted cookie store use?
- Are cookie names encrypted, or only the content?
- What is the structure of a signed cookie? If I want to read it using JavaScript, how to do it?

**Comment by ellmetha** [comment]
Thanks for flagging this!

Additional documentation around cookies was introduced in martenframework/marten@db18167, which covers these points. We can close this issue now.
